---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-stack-playground
  namespace: {{ .Values.username }}-llama-stack
  labels:
    app.kubernetes.io/name: llama-stack-playground
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"llama-stack-playground"}}'
